prog_names = {
    'ast': "Astronomija",
    'fiz': "Fizika",
    'mat': 'Matematika',
    'pfe': 'Primenjena fizika i elektronika',
    'ele': 'Elektronika',
    'rac': 'Računarstvo',
    'bio': 'Biologija',
    'bmd': 'Biomedicina',
    'hbh': 'Humana biohemija',
    'glg': 'Geologija',
    'geo': 'Geografija',
    'hem': 'Hemija',
    'ska': 'Sociokulturna antropologija',
    'fan': 'Fizička antropologija',
    'ant': 'Antropologija',
    'etn': 'Etnologija',
    'ahl': 'Arheologija',
    'drh': 'Društveno-humanističke nauke',
    'ist': 'Istorija',
    'lin': 'Lingvistika',
    'psh': 'Psihologija',
    'diz': 'Dizajn',
    'gst': 'Gosti'
}